name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setting up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant permissions
        run: sudo chmod -R 777 Builder/

      - name: Setup and build
        run:  cd Builder/src/cn/yapeteam/builder & sudo javac Builder.java & sudo javac OS.java & sudo javac ProcessBar.java & sudo javac SSLUtils.java & sudo jar cvf Builder.jar ../../../META-INF/MANIFEST.MF ./cn/yapeteam/builder & cd ../../../../.. & sudo java -jar Builder/src/Builder.jar release
        
      - name: Upload artifact
        run: |
          cd build/libs
          export JAR=$(find . 'injector.jar')
          curl --connect-timeout 30 -m 300 -X POST -F "artifact=@injector.jar" -H "Authorization: ${{ secrets.NIGHTLY_PASS }}" -F "gh_id=${{ github.event.head_commit.id }}" -F "gh_ref=${{ github.ref }}" -F "gh_message=${{ github.event.head_commit.message }}" -F "gh_timestamp=${{ github.event.head_commit.timestamp }}"

  verify-pr:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setting up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant permissions
        run: sudo chmod -R 777 Builder/

      - name: Setup and build
        run: sudo java Builder/src/cn/yapeteam/builder/Builder.java release
